#!/usr/local/bin/python3

"""
VPN Link — Backend service script.

Handles DNS ACL synchronization for WireGuard tunnel subnets.
Supports both Unbound-only and AdGuard Home + Unbound setups:

  - Unbound only:  WG client -> Unbound (:53) -> upstream
  - AdGuard setup: WG client -> AdGuard (:53) -> Unbound (:5353) -> upstream

For Unbound: generates access-control directives in an include file.
For AdGuard: patches AdGuard's bind_hosts to include WG interface IPs
             so it accepts DNS queries from the WG subnet.

Usage:
    vpnlink.py start        Apply DNS ACL and firewall rules
    vpnlink.py stop         Remove DNS ACL file
    vpnlink.py restart      Re-apply everything
    vpnlink.py status       Show current state
    vpnlink.py sync_dns     Sync DNS ACL (Unbound + AdGuard if detected)
"""

import json
import os
import subprocess
import sys
import ipaddress
import copy

UNBOUND_ACL_FILE = '/var/unbound/vpnlink_acl.conf'
ADGUARD_CONFIG_PATHS = [
    '/usr/local/AdGuardHome/AdGuardHome.yaml',
    '/var/db/adguardhome/AdGuardHome.yaml',
    '/usr/local/etc/adguardhome/AdGuardHome.yaml',
]
WG_SHOW_CMD = '/usr/bin/wg'


def discover_wg_subnets():
    """Discover WireGuard tunnel subnets from wg show output and interface config."""
    subnets = set()

    # Method 1: Parse `wg show` for interface addresses
    try:
        result = subprocess.run(
            [WG_SHOW_CMD, 'show', 'interfaces'],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            interfaces = result.stdout.strip().split()
            for iface in interfaces:
                addrs = get_interface_addresses(iface)
                for addr in addrs:
                    try:
                        network = ipaddress.ip_network(addr, strict=False)
                        if network.version == 4:
                            subnets.add(str(network))
                    except ValueError:
                        pass
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass

    # Method 2: Read from OPNsense config.xml via configd
    if not subnets:
        subnets = discover_from_config()

    return sorted(subnets)


def get_interface_addresses(iface):
    """Get IP addresses assigned to a network interface."""
    addresses = []
    try:
        result = subprocess.run(
            ['ifconfig', iface],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            for line in result.stdout.splitlines():
                line = line.strip()
                if line.startswith('inet '):
                    parts = line.split()
                    ip = parts[1]
                    # Look for netmask
                    if 'netmask' in parts:
                        idx = parts.index('netmask')
                        netmask_hex = parts[idx + 1]
                        # Convert hex netmask to prefix length
                        try:
                            mask_int = int(netmask_hex, 16)
                            prefix = bin(mask_int).count('1')
                            addresses.append('{}/{}'.format(ip, prefix))
                        except ValueError:
                            addresses.append('{}/24'.format(ip))
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass
    return addresses


def discover_from_config():
    """Fallback: read WireGuard config from OPNsense config.xml."""
    subnets = set()
    config_path = '/conf/config.xml'

    if not os.path.exists(config_path):
        return subnets

    try:
        import xml.etree.ElementTree as ET
        tree = ET.parse(config_path)
        root = tree.getroot()

        # Look for interfaces with wg* device names
        interfaces = root.find('interfaces')
        if interfaces is not None:
            for iface in interfaces:
                if_dev = iface.find('if')
                if if_dev is not None and if_dev.text and if_dev.text.startswith('wg'):
                    ipaddr = iface.find('ipaddr')
                    subnet = iface.find('subnet')
                    if ipaddr is not None and subnet is not None:
                        if ipaddr.text and subnet.text:
                            try:
                                addr = '{}/{}'.format(ipaddr.text, subnet.text)
                                network = ipaddress.ip_network(addr, strict=False)
                                if network.version == 4:
                                    subnets.add(str(network))
                            except ValueError:
                                pass
    except Exception as e:
        syslog_msg('Error reading config: {}'.format(e))

    return subnets


def generate_unbound_acl(subnets):
    """Write Unbound access-control directives for WG subnets."""
    lines = [
        '# Auto-generated by VPN Link — do not edit manually',
        '# Allows WireGuard VPN clients to query Unbound DNS',
        '',
    ]

    for subnet in subnets:
        lines.append('access-control: {} allow'.format(subnet))

    lines.append('')

    acl_dir = os.path.dirname(UNBOUND_ACL_FILE)
    if not os.path.isdir(acl_dir):
        return False

    try:
        with open(UNBOUND_ACL_FILE, 'w') as f:
            f.write('\n'.join(lines))
        return True
    except IOError as e:
        syslog_msg('Error writing ACL: {}'.format(e))
        return False


def remove_unbound_acl():
    """Remove the Unbound ACL file."""
    try:
        if os.path.exists(UNBOUND_ACL_FILE):
            os.unlink(UNBOUND_ACL_FILE)
    except IOError:
        pass


def reload_unbound():
    """Restart Unbound to pick up ACL changes."""
    try:
        subprocess.run(
            ['configctl', 'unbound', 'restart'],
            capture_output=True, timeout=30
        )
    except (subprocess.TimeoutExpired, FileNotFoundError):
        try:
            subprocess.run(
                ['service', 'unbound', 'restart'],
                capture_output=True, timeout=30
            )
        except (subprocess.TimeoutExpired, FileNotFoundError):
            pass


# ── AdGuard Home integration ──────────────────────────────────────────


def detect_adguard():
    """Detect if AdGuard Home is installed. Returns config path or None."""
    for path in ADGUARD_CONFIG_PATHS:
        if os.path.exists(path):
            return path

    # Check if AdGuard process is running
    try:
        result = subprocess.run(
            ['pgrep', '-f', 'AdGuardHome'],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            # Try to find config via process args
            ps_result = subprocess.run(
                ['ps', 'aux'],
                capture_output=True, text=True, timeout=5
            )
            for line in ps_result.stdout.splitlines():
                if 'AdGuardHome' in line and '-c' in line:
                    parts = line.split()
                    for i, p in enumerate(parts):
                        if p == '-c' and i + 1 < len(parts):
                            cfg = parts[i + 1]
                            if os.path.exists(cfg):
                                return cfg
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass

    return None


def get_dns_topology():
    """Read DNS topology setting from OPNsense config.xml."""
    config_path = '/conf/config.xml'
    if not os.path.exists(config_path):
        return 'auto'

    try:
        import xml.etree.ElementTree as ET
        tree = ET.parse(config_path)
        root = tree.getroot()
        node = root.find('.//OPNsense/VPNLink/general/dnsTopology')
        if node is not None and node.text:
            return node.text
    except Exception:
        pass

    return 'auto'


def get_wg_interface_ips():
    """Get the IP addresses of all WireGuard interfaces (the server-side IPs)."""
    ips = []
    try:
        result = subprocess.run(
            [WG_SHOW_CMD, 'show', 'interfaces'],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            interfaces = result.stdout.strip().split()
            for iface in interfaces:
                addrs = get_interface_addresses(iface)
                for addr in addrs:
                    ip = addr.split('/')[0]
                    ips.append(ip)
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    return ips


def sync_adguard_binds(adguard_config_path, wg_ips):
    """
    Ensure AdGuard Home listens on WG interface IPs.

    AdGuard's bind_hosts controls which IPs it accepts DNS queries on.
    We add WG interface IPs so VPN clients can reach AdGuard.

    Returns True if config was changed and AdGuard needs restart.
    """
    try:
        import yaml
    except ImportError:
        # PyYAML not available — try manual patching
        return sync_adguard_binds_manual(adguard_config_path, wg_ips)

    try:
        with open(adguard_config_path, 'r') as f:
            config = yaml.safe_load(f)
    except Exception as e:
        syslog_msg('AdGuard: Error reading config: {}'.format(e))
        return False

    if not isinstance(config, dict) or 'dns' not in config:
        syslog_msg('AdGuard: Invalid config format')
        return False

    dns = config['dns']
    bind_hosts = dns.get('bind_hosts', [])

    # If bind_hosts contains 0.0.0.0 it's already listening on all interfaces
    if '0.0.0.0' in bind_hosts:
        syslog_msg('AdGuard: Already bound to 0.0.0.0, no changes needed')
        return False

    original_binds = list(bind_hosts)
    changed = False

    for ip in wg_ips:
        if ip not in bind_hosts:
            bind_hosts.append(ip)
            changed = True

    if not changed:
        return False

    dns['bind_hosts'] = bind_hosts
    config['dns'] = dns

    try:
        with open(adguard_config_path, 'w') as f:
            yaml.dump(config, f, default_flow_style=False)
        syslog_msg('AdGuard: Added WG IPs to bind_hosts: {} (was: {})'.format(
            bind_hosts, original_binds))
        return True
    except Exception as e:
        syslog_msg('AdGuard: Error writing config: {}'.format(e))
        return False


def sync_adguard_binds_manual(adguard_config_path, wg_ips):
    """Fallback: patch AdGuard config without PyYAML (simple text-based)."""
    try:
        with open(adguard_config_path, 'r') as f:
            content = f.read()
    except IOError:
        return False

    # Check if already bound to all
    if '0.0.0.0' in content and 'bind_hosts' in content:
        return False

    changed = False
    for ip in wg_ips:
        marker = '  - {}'.format(ip)
        if marker not in content and ip not in content:
            # Find bind_hosts section and append
            # This is fragile but works as fallback
            syslog_msg('AdGuard: PyYAML not available. Please manually add {} to bind_hosts in {}'.format(
                ip, adguard_config_path))
            changed = True

    return False  # Don't auto-modify without YAML parser


def restart_adguard():
    """Restart AdGuard Home service."""
    try:
        subprocess.run(
            ['service', 'AdGuardHome', 'restart'],
            capture_output=True, timeout=30
        )
    except (subprocess.TimeoutExpired, FileNotFoundError):
        try:
            subprocess.run(
                ['configctl', 'adguardhome', 'restart'],
                capture_output=True, timeout=30
            )
        except (subprocess.TimeoutExpired, FileNotFoundError):
            pass


def syslog_msg(msg):
    """Log a message to syslog."""
    try:
        import syslog
        syslog.openlog('vpnlink', syslog.LOG_PID, syslog.LOG_LOCAL4)
        syslog.syslog(syslog.LOG_INFO, msg)
    except Exception:
        pass


def resolve_dns_topology():
    """Determine effective DNS topology (auto-detect or user setting)."""
    setting = get_dns_topology()

    if setting != 'auto':
        adguard_cfg = detect_adguard() if setting == 'adguard_unbound' else None
        return setting, adguard_cfg

    # Auto-detect
    adguard_cfg = detect_adguard()
    if adguard_cfg:
        return 'adguard_unbound', adguard_cfg
    return 'unbound', None


def cmd_start():
    """Apply DNS ACL (Unbound + AdGuard if applicable)."""
    subnets = discover_wg_subnets()
    if not subnets:
        syslog_msg('Started: No WireGuard subnets discovered')
        return

    topology, adguard_cfg = resolve_dns_topology()

    # Always sync Unbound ACL (harmless even with AdGuard in front)
    generate_unbound_acl(subnets)
    reload_unbound()

    # If AdGuard detected, ensure it listens on WG interface IPs
    if topology == 'adguard_unbound' and adguard_cfg:
        wg_ips = get_wg_interface_ips()
        if wg_ips:
            changed = sync_adguard_binds(adguard_cfg, wg_ips)
            if changed:
                restart_adguard()

    syslog_msg('Started: DNS ACL applied for subnets: {} (topology: {})'.format(
        ', '.join(subnets), topology))


def cmd_stop():
    """Remove DNS ACL."""
    remove_unbound_acl()
    reload_unbound()
    syslog_msg('Stopped: DNS ACL removed')


def cmd_restart():
    """Re-apply everything."""
    cmd_stop()
    cmd_start()


def cmd_status():
    """Show current status."""
    subnets = discover_wg_subnets()
    acl_exists = os.path.exists(UNBOUND_ACL_FILE)
    topology, adguard_cfg = resolve_dns_topology()

    status = {
        'running': acl_exists,
        'subnets': subnets,
        'acl_file': UNBOUND_ACL_FILE,
        'acl_exists': acl_exists,
        'dns_topology': topology,
        'adguard_detected': adguard_cfg is not None,
        'adguard_config': adguard_cfg,
        'wg_interface_ips': get_wg_interface_ips(),
    }

    print(json.dumps(status, indent=2))


def cmd_sync_dns():
    """Sync DNS ACL — Unbound + AdGuard if detected (called on VPN events)."""
    subnets = discover_wg_subnets()
    if not subnets:
        syslog_msg('DNS sync: No WireGuard subnets discovered')
        return

    topology, adguard_cfg = resolve_dns_topology()

    # Sync Unbound ACL
    old_content = ''
    if os.path.exists(UNBOUND_ACL_FILE):
        with open(UNBOUND_ACL_FILE, 'r') as f:
            old_content = f.read()

    generate_unbound_acl(subnets)

    new_content = ''
    with open(UNBOUND_ACL_FILE, 'r') as f:
        new_content = f.read()

    if old_content != new_content:
        reload_unbound()
        syslog_msg('DNS ACL updated for subnets: {}'.format(', '.join(subnets)))

    # Sync AdGuard bind_hosts
    if topology == 'adguard_unbound' and adguard_cfg:
        wg_ips = get_wg_interface_ips()
        if wg_ips:
            changed = sync_adguard_binds(adguard_cfg, wg_ips)
            if changed:
                restart_adguard()
                syslog_msg('AdGuard bind_hosts updated for WG IPs: {}'.format(
                    ', '.join(wg_ips)))


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Usage: vpnlink.py {start|stop|restart|status|sync_dns}')
        sys.exit(1)

    cmd = sys.argv[1]
    commands = {
        'start': cmd_start,
        'stop': cmd_stop,
        'restart': cmd_restart,
        'status': cmd_status,
        'sync_dns': cmd_sync_dns,
    }

    if cmd in commands:
        commands[cmd]()
    else:
        print('Unknown command: {}'.format(cmd))
        sys.exit(1)
