[start]
command:/usr/local/opnsense/scripts/OPNsense/VPNLink/vpnlink.py start
parameters:
type:script
message:starting vpnlink

[stop]
command:/usr/local/opnsense/scripts/OPNsense/VPNLink/vpnlink.py stop
parameters:
type:script
message:stopping vpnlink

[restart]
command:/usr/local/opnsense/scripts/OPNsense/VPNLink/vpnlink.py restart
parameters:
type:script
message:restarting vpnlink
description:Restart VPN Link

[status]
command:/usr/local/opnsense/scripts/OPNsense/VPNLink/vpnlink.py status
parameters:
type:script_output
message:show vpnlink status

[sync_dns]
command:/usr/local/opnsense/scripts/OPNsense/VPNLink/vpnlink.py sync_dns
parameters:
type:script
message:syncing vpnlink dns acl
description:Sync VPN Link DNS ACL
