[start]
command:/usr/local/opnsense/scripts/OPNsense/Vpnlink/vpnlink.py start
parameters:
type:script
message:starting vpnlink

[stop]
command:/usr/local/opnsense/scripts/OPNsense/Vpnlink/vpnlink.py stop
parameters:
type:script
message:stopping vpnlink

[restart]
command:/usr/local/opnsense/scripts/OPNsense/Vpnlink/vpnlink.py restart
parameters:
type:script
message:restarting vpnlink
description:Restart VPN Link

[status]
command:/usr/local/opnsense/scripts/OPNsense/Vpnlink/vpnlink.py status
parameters:
type:script_output
message:show vpnlink status

[sync_dns]
command:/usr/local/opnsense/scripts/OPNsense/Vpnlink/vpnlink.py sync_dns
parameters:
type:script
message:syncing vpnlink dns acl
description:Sync VPN Link DNS ACL

[healthcheck]
command:/usr/local/opnsense/scripts/OPNsense/Vpnlink/vpnlink.py healthcheck
parameters:
type:script_output
message:vpnlink health check

[log]
command:/usr/local/opnsense/scripts/OPNsense/Vpnlink/vpnlink.py log
parameters:
type:script_output
message:vpnlink log

[collect_traffic]
command:/usr/local/opnsense/scripts/OPNsense/Vpnlink/collect_traffic.py
parameters:
type:script
message:collecting vpnlink traffic data

[traffic_summary]
command:/usr/local/opnsense/scripts/OPNsense/Vpnlink/collect_traffic.py summary
parameters:
type:script_output
message:vpnlink traffic summary

[traffic_history]
command:/usr/local/opnsense/scripts/OPNsense/Vpnlink/collect_traffic.py history
parameters:%s
type:script_output
message:vpnlink traffic history
